// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protocol/ServerMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from protocol/ServerMessages.proto</summary>
public static partial class ServerMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for protocol/ServerMessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServerMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1wcm90b2NvbC9TZXJ2ZXJNZXNzYWdlcy5wcm90byIxChBSZXNvbHV0aW9u",
          "Q2hhbmdlEg0KBXdpZHRoGAEgAigFEg4KBmhlaWdodBgCIAIoBSJjCg9Db25u",
          "ZWN0aW9uUmVwbHkSEAoIYWNjZXB0ZWQYASACKAgSEQoJdmlkZW9Qb3J0GAIg",
          "ASgFEisKEHJlc29sdXRpb25DaGFuZ2UYAyABKAsyES5SZXNvbHV0aW9uQ2hh",
          "bmdlInIKDVNlcnZlck1lc3NhZ2USKwoPQ29ubmVjdGlvblJlcGx5GAEgASgL",
          "MhAuQ29ubmVjdGlvblJlcGx5SAASLQoQUmVzb2x1dGlvbkNoYW5nZRgCIAEo",
          "CzIRLlJlc29sdXRpb25DaGFuZ2VIAEIFCgNNc2c="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ResolutionChange), global::ResolutionChange.Parser, new[]{ "Width", "Height" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ConnectionReply), global::ConnectionReply.Parser, new[]{ "Accepted", "VideoPort", "ResolutionChange" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerMessage), global::ServerMessage.Parser, new[]{ "ConnectionReply", "ResolutionChange" }, new[]{ "Msg" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ResolutionChange : pb::IMessage<ResolutionChange>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ResolutionChange> _parser = new pb::MessageParser<ResolutionChange>(() => new ResolutionChange());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ResolutionChange> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ResolutionChange() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ResolutionChange(ResolutionChange other) : this() {
    _hasBits0 = other._hasBits0;
    width_ = other.width_;
    height_ = other.height_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ResolutionChange Clone() {
    return new ResolutionChange(this);
  }

  /// <summary>Field number for the "width" field.</summary>
  public const int WidthFieldNumber = 1;
  private readonly static int WidthDefaultValue = 0;

  private int width_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Width {
    get { if ((_hasBits0 & 1) != 0) { return width_; } else { return WidthDefaultValue; } }
    set {
      _hasBits0 |= 1;
      width_ = value;
    }
  }
  /// <summary>Gets whether the "width" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasWidth {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "width" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearWidth() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "height" field.</summary>
  public const int HeightFieldNumber = 2;
  private readonly static int HeightDefaultValue = 0;

  private int height_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Height {
    get { if ((_hasBits0 & 2) != 0) { return height_; } else { return HeightDefaultValue; } }
    set {
      _hasBits0 |= 2;
      height_ = value;
    }
  }
  /// <summary>Gets whether the "height" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasHeight {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "height" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearHeight() {
    _hasBits0 &= ~2;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ResolutionChange);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ResolutionChange other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Width != other.Width) return false;
    if (Height != other.Height) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasWidth) hash ^= Width.GetHashCode();
    if (HasHeight) hash ^= Height.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasWidth) {
      output.WriteRawTag(8);
      output.WriteInt32(Width);
    }
    if (HasHeight) {
      output.WriteRawTag(16);
      output.WriteInt32(Height);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasWidth) {
      output.WriteRawTag(8);
      output.WriteInt32(Width);
    }
    if (HasHeight) {
      output.WriteRawTag(16);
      output.WriteInt32(Height);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasWidth) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
    }
    if (HasHeight) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ResolutionChange other) {
    if (other == null) {
      return;
    }
    if (other.HasWidth) {
      Width = other.Width;
    }
    if (other.HasHeight) {
      Height = other.Height;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Width = input.ReadInt32();
          break;
        }
        case 16: {
          Height = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Width = input.ReadInt32();
          break;
        }
        case 16: {
          Height = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ConnectionReply : pb::IMessage<ConnectionReply>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ConnectionReply> _parser = new pb::MessageParser<ConnectionReply>(() => new ConnectionReply());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ConnectionReply> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectionReply() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectionReply(ConnectionReply other) : this() {
    _hasBits0 = other._hasBits0;
    accepted_ = other.accepted_;
    videoPort_ = other.videoPort_;
    resolutionChange_ = other.resolutionChange_ != null ? other.resolutionChange_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ConnectionReply Clone() {
    return new ConnectionReply(this);
  }

  /// <summary>Field number for the "accepted" field.</summary>
  public const int AcceptedFieldNumber = 1;
  private readonly static bool AcceptedDefaultValue = false;

  private bool accepted_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Accepted {
    get { if ((_hasBits0 & 1) != 0) { return accepted_; } else { return AcceptedDefaultValue; } }
    set {
      _hasBits0 |= 1;
      accepted_ = value;
    }
  }
  /// <summary>Gets whether the "accepted" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAccepted {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "accepted" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAccepted() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "videoPort" field.</summary>
  public const int VideoPortFieldNumber = 2;
  private readonly static int VideoPortDefaultValue = 0;

  private int videoPort_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int VideoPort {
    get { if ((_hasBits0 & 2) != 0) { return videoPort_; } else { return VideoPortDefaultValue; } }
    set {
      _hasBits0 |= 2;
      videoPort_ = value;
    }
  }
  /// <summary>Gets whether the "videoPort" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasVideoPort {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "videoPort" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearVideoPort() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "resolutionChange" field.</summary>
  public const int ResolutionChangeFieldNumber = 3;
  private global::ResolutionChange resolutionChange_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ResolutionChange ResolutionChange {
    get { return resolutionChange_; }
    set {
      resolutionChange_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ConnectionReply);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ConnectionReply other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Accepted != other.Accepted) return false;
    if (VideoPort != other.VideoPort) return false;
    if (!object.Equals(ResolutionChange, other.ResolutionChange)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasAccepted) hash ^= Accepted.GetHashCode();
    if (HasVideoPort) hash ^= VideoPort.GetHashCode();
    if (resolutionChange_ != null) hash ^= ResolutionChange.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasAccepted) {
      output.WriteRawTag(8);
      output.WriteBool(Accepted);
    }
    if (HasVideoPort) {
      output.WriteRawTag(16);
      output.WriteInt32(VideoPort);
    }
    if (resolutionChange_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(ResolutionChange);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasAccepted) {
      output.WriteRawTag(8);
      output.WriteBool(Accepted);
    }
    if (HasVideoPort) {
      output.WriteRawTag(16);
      output.WriteInt32(VideoPort);
    }
    if (resolutionChange_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(ResolutionChange);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasAccepted) {
      size += 1 + 1;
    }
    if (HasVideoPort) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(VideoPort);
    }
    if (resolutionChange_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResolutionChange);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ConnectionReply other) {
    if (other == null) {
      return;
    }
    if (other.HasAccepted) {
      Accepted = other.Accepted;
    }
    if (other.HasVideoPort) {
      VideoPort = other.VideoPort;
    }
    if (other.resolutionChange_ != null) {
      if (resolutionChange_ == null) {
        ResolutionChange = new global::ResolutionChange();
      }
      ResolutionChange.MergeFrom(other.ResolutionChange);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Accepted = input.ReadBool();
          break;
        }
        case 16: {
          VideoPort = input.ReadInt32();
          break;
        }
        case 26: {
          if (resolutionChange_ == null) {
            ResolutionChange = new global::ResolutionChange();
          }
          input.ReadMessage(ResolutionChange);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Accepted = input.ReadBool();
          break;
        }
        case 16: {
          VideoPort = input.ReadInt32();
          break;
        }
        case 26: {
          if (resolutionChange_ == null) {
            ResolutionChange = new global::ResolutionChange();
          }
          input.ReadMessage(ResolutionChange);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ServerMessage : pb::IMessage<ServerMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerMessage> _parser = new pb::MessageParser<ServerMessage>(() => new ServerMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerMessage(ServerMessage other) : this() {
    switch (other.MsgCase) {
      case MsgOneofCase.ConnectionReply:
        ConnectionReply = other.ConnectionReply.Clone();
        break;
      case MsgOneofCase.ResolutionChange:
        ResolutionChange = other.ResolutionChange.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerMessage Clone() {
    return new ServerMessage(this);
  }

  /// <summary>Field number for the "ConnectionReply" field.</summary>
  public const int ConnectionReplyFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ConnectionReply ConnectionReply {
    get { return msgCase_ == MsgOneofCase.ConnectionReply ? (global::ConnectionReply) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ConnectionReply;
    }
  }

  /// <summary>Field number for the "ResolutionChange" field.</summary>
  public const int ResolutionChangeFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ResolutionChange ResolutionChange {
    get { return msgCase_ == MsgOneofCase.ResolutionChange ? (global::ResolutionChange) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ResolutionChange;
    }
  }

  private object msg_;
  /// <summary>Enum of possible cases for the "Msg" oneof.</summary>
  public enum MsgOneofCase {
    None = 0,
    ConnectionReply = 1,
    ResolutionChange = 2,
  }
  private MsgOneofCase msgCase_ = MsgOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MsgOneofCase MsgCase {
    get { return msgCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMsg() {
    msgCase_ = MsgOneofCase.None;
    msg_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ConnectionReply, other.ConnectionReply)) return false;
    if (!object.Equals(ResolutionChange, other.ResolutionChange)) return false;
    if (MsgCase != other.MsgCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (msgCase_ == MsgOneofCase.ConnectionReply) hash ^= ConnectionReply.GetHashCode();
    if (msgCase_ == MsgOneofCase.ResolutionChange) hash ^= ResolutionChange.GetHashCode();
    hash ^= (int) msgCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (msgCase_ == MsgOneofCase.ConnectionReply) {
      output.WriteRawTag(10);
      output.WriteMessage(ConnectionReply);
    }
    if (msgCase_ == MsgOneofCase.ResolutionChange) {
      output.WriteRawTag(18);
      output.WriteMessage(ResolutionChange);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (msgCase_ == MsgOneofCase.ConnectionReply) {
      output.WriteRawTag(10);
      output.WriteMessage(ConnectionReply);
    }
    if (msgCase_ == MsgOneofCase.ResolutionChange) {
      output.WriteRawTag(18);
      output.WriteMessage(ResolutionChange);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (msgCase_ == MsgOneofCase.ConnectionReply) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectionReply);
    }
    if (msgCase_ == MsgOneofCase.ResolutionChange) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResolutionChange);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerMessage other) {
    if (other == null) {
      return;
    }
    switch (other.MsgCase) {
      case MsgOneofCase.ConnectionReply:
        if (ConnectionReply == null) {
          ConnectionReply = new global::ConnectionReply();
        }
        ConnectionReply.MergeFrom(other.ConnectionReply);
        break;
      case MsgOneofCase.ResolutionChange:
        if (ResolutionChange == null) {
          ResolutionChange = new global::ResolutionChange();
        }
        ResolutionChange.MergeFrom(other.ResolutionChange);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::ConnectionReply subBuilder = new global::ConnectionReply();
          if (msgCase_ == MsgOneofCase.ConnectionReply) {
            subBuilder.MergeFrom(ConnectionReply);
          }
          input.ReadMessage(subBuilder);
          ConnectionReply = subBuilder;
          break;
        }
        case 18: {
          global::ResolutionChange subBuilder = new global::ResolutionChange();
          if (msgCase_ == MsgOneofCase.ResolutionChange) {
            subBuilder.MergeFrom(ResolutionChange);
          }
          input.ReadMessage(subBuilder);
          ResolutionChange = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::ConnectionReply subBuilder = new global::ConnectionReply();
          if (msgCase_ == MsgOneofCase.ConnectionReply) {
            subBuilder.MergeFrom(ConnectionReply);
          }
          input.ReadMessage(subBuilder);
          ConnectionReply = subBuilder;
          break;
        }
        case 18: {
          global::ResolutionChange subBuilder = new global::ResolutionChange();
          if (msgCase_ == MsgOneofCase.ResolutionChange) {
            subBuilder.MergeFrom(ResolutionChange);
          }
          input.ReadMessage(subBuilder);
          ResolutionChange = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
